name: mlmdiary
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+5 

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  get: ^4.6.6
  intl: ^0.18.1
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.5
  flutter_otp_text_field: ^1.1.3+2
  country_calling_code_picker: ^2.0.1
  image_picker: ^1.1.2
  image_cropper: ^7.1.0
  share_plus: ^9.0.0
  path_provider: ^2.1.3
  http: ^1.2.1
  toastification: ^2.0.0
  flutter_image_compress: ^2.3.0
  connectivity_plus: ^6.0.3
  flutter_google_places_hoc081098: ^2.0.0-beta.1
  shared_preferences: ^2.2.3
  flutter_html: ^3.0.0-beta.2
  http_parser: ^4.0.2
  cached_network_image: ^3.3.1
  webview_flutter: ^4.8.0
  url_launcher: ^6.3.0
  youtube_player_iframe: ^5.1.2
  html_unescape: ^2.0.0
  video_player: ^2.8.6
  text_link: ^1.0.0
  html: ^0.15.4
  textfield_tags: ^3.0.1
  firebase_core: any
  firebase_auth: ^5.1.0
  firebase_messaging: any
  uuid: ^4.4.0
  device_info_plus: ^10.1.0
  flutter_local_notifications: ^17.1.2
  firebase_analytics: ^11.1.0
  package_info_plus: ^4.2.0
  lottie: ^3.1.2
  gtm: ^0.1.6
  facebook_app_events: ^0.19.2
  flutter_widget_from_html: ^0.15.2
  shimmer: ^3.0.0
  pinput: ^5.0.0
  firebase_dynamic_links: ^6.0.5
  app_links: ^6.3.3
  scrollable_tab_view: ^1.0.13
  smart_auth: ^2.0.0


  


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/lottie/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.otf
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf
