// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMDHhyPn6uiMPVWEU7Ti5-01QIVT5e-fE',
    appId: '1:756619884404:web:6e93de9b14ffebd31ade21',
    messagingSenderId: '756619884404',
    projectId: 'mlm-diary',
    authDomain: 'mlm-diary.firebaseapp.com',
    storageBucket: 'mlm-diary.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR4pYNkAPbUwv54SsH54QXkMxr9E1Ygvs',
    appId: '1:756619884404:android:3cfc4b25051f789d1ade21',
    messagingSenderId: '756619884404',
    projectId: 'mlm-diary',
    storageBucket: 'mlm-diary.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3G5O1TgW9dBeXYPmF54jWbeLMSkyCPDA',
    appId: '1:756619884404:ios:708d81bfac1eece11ade21',
    messagingSenderId: '756619884404',
    projectId: 'mlm-diary',
    storageBucket: 'mlm-diary.appspot.com',
    iosBundleId: 'com.example.mlmdiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3G5O1TgW9dBeXYPmF54jWbeLMSkyCPDA',
    appId: '1:756619884404:ios:708d81bfac1eece11ade21',
    messagingSenderId: '756619884404',
    projectId: 'mlm-diary',
    storageBucket: 'mlm-diary.appspot.com',
    iosBundleId: 'com.example.mlmdiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMDHhyPn6uiMPVWEU7Ti5-01QIVT5e-fE',
    appId: '1:756619884404:web:2d43a301e5cfed7f1ade21',
    messagingSenderId: '756619884404',
    projectId: 'mlm-diary',
    authDomain: 'mlm-diary.firebaseapp.com',
    storageBucket: 'mlm-diary.appspot.com',
  );
}
